### ISSUE TITLE
Wrong class/enum used SI114X_CMD.RD - doesn't exist

### ISSUE THREAD

**Issue by pezi** [Seeed-Studio/Seeed_Python_SI114X#3]
Converting this python code 
https://github.com/Seeed-Studio/Seeed_Python_SI114X/blob/master/seeed_si114x.py#L232)
to Dart
https://github.com/pezi/dart_periphery/blob/ps/0.9.10_fix/lib/src/hardware/si1145.dart

I found following error

```python
    #read param data
    def ReadParamData(self,Reg):
        self._WriteByte(SI114X_REG.COMMAND, Reg | SI114X_CMD.QUERY)
        # return self._ReadByte(SI114X_CMD.RD) doesn't exist
        
        # Fix
        return self._ReadByte(SI114X_REG.RD) 
```

**Comment by Lesords** [comment]
@is-qian Help with this one.

**Comment by is-qian** [comment]
Thank you for pointing that out. It does seem there's an issue. I will find a sensor to make modifications and verify it. Thank you again.
